apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-async-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync-async-bridge
  template:
    metadata:
      labels:
        app: sync-async-bridge
    spec:
      containers:
      - name: sync-async-bridge
        image: ortaieb/sync-async-bridge:0.1.6
        env:
        - name: QUARKUS_HTTP_PORT
          value: "9999"
        - name: QUARKUS_GRPC_SERVER_PORT
          value: "9999"
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 9999
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sync-async-bridge-svc
spec:
  selector:
    app: sync-async-bridge
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      name: grpc-http-9999
  type: NodePort
